### ISSUE TITLE
Errors when going from fastify 2 to fastify 3

### ISSUE THREAD

**Issue by mitry1974** [dimonnwc3/fastify-reverse-routes#4]
Hello!
After update versions of packages fastify and all other corresponding plugins and got error on start:
"Error: Route with name [object Object] is not registered at reverse (/home/mt/dev/backend-project-lvl4/node_modules/fastify-reverse-routes/index.js:10:11)".

what happens? How to fix it?

Thank you!

**Comment by dimonnwc3** [comment]
I can't reproduce this error.
I believe you should update this package to the 2 versions too if you haven't done it yet

**Comment by mitry1974** [comment]
Thank you for the answer, I will doublecheck
